site_name: Architecture Docs
theme: material
nav:
  - Home: index.md
  # - ADRs:
  #     - 0001: adr/0001-record-architecture-decisions.md
  #     - 0002: adr/0002-use-rest-api.md
  # - C4 Diagrams:
  #     - Context: c4model/context.md
