site_name: Simelabs Architecture Docs
site_url: https://anoopsimelabs.github.io/architecture-docs/

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

nav:
  - PAPI:
      - ADRs:
          - 0001. Database Schema Refactoring: adr/db-schema-refactoring.md
          - 0002. Migrate to SpringBoot service: adr/migrate-to-springboot.md
          - 0003. Use MUI Design system: adr/use-mui.md
          - 0004. Converting long forms: adr/convert-long-forms.md
      - Draft ADRs:
          - 0005. Include Fitness Functions: adr/include-fitness-functions.md
      - Diagrams:
          - Context (Existing): diagrams/context.md
          - Context (Proposed): diagrams/proposed-context.md
          - Container (Existing): diagrams/existing-container.md
          - Container (Proposed): diagrams/proposed-container.md
          - Entity Relationship Diagram: diagrams/erd.md
      - Others:
          - Tables and Field Counts: others/tables-and-field-counts.md
          - API Endpoints: others/api-endpoints.md

plugins:
  - search
  - mermaid2 # Enables Mermaid diagram support

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
# extra_javascript:
#   - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
