site_name: Simelabs Architecture Docs
site_url: https://anoopsimelabs.github.io/architecture-docs/

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.tabs.link
    - content.action.edit

nav:
  - PAPI:
      - ADRs:
          - 0001. Migrate to SpringBoot service: adr/0001-migrate-to-springboot.md
          - 0002. Use MUI Design system: adr/0002-use-mui.md
          - 0003. Converting long forms: adr/0003-convert-long-forms.md
      - Diagrams:
          - Context: diagrams/context.md
          - Container (Existing): diagrams/existing-container.md
          - Container (Proposed): diagrams/proposed-container.md

plugins:
  - search
  - mermaid2 # Enables Mermaid diagram support

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
# extra_javascript:
#   - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
