site_name: Simelabs Architecture Docs
site_url: https://anoopsimelabs.github.io/architecture-docs/
repo_url: https://github.com/anoopsimelabs/architecture-docs
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.sections
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - toc.integrate
    - navigation.top
    - navigation.expand
    - navigation.instant
    - navigation.tracking

nav:
  - PAPI ADRs:
      - 0001. Migrate to SpringBoot service: adr/0001-migrate-to-springboot.md
      - 0002. Use MUI Design system: adr/0002-use-mui.md
      - 0003. Converting long forms: adr/0003-convert-long-forms.md
  - PAPI Diagrams:
      - Context: diagrams/context.md

plugins:
  - search
  - mermaid2 # Enables Mermaid diagram support

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
