name: Deploy Docs

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Deploy MkDocs site to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
      - name: Clean up
        run: |
          echo "Cleaning up..."
          rm -rf site
          echo "Cleanup complete."
      - name: Notify completion
        run: |
          echo "Deployment completed successfully!"
          echo "You can view the documentation at: https://<your-username>.github.io/<your-repo-name>/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_API_URL: ${{ github.api_url }}
          GITHUB_GRAPHQL_URL: ${{ github.graphql_url }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_REPOSITORY_URL: ${{ github.event.repository.html_url }}
          GITHUB_REPOSITORY_DESCRIPTION: ${{ github.event.repository.description }}
