name: Deploy Docs

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Deploy MkDocs site to GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
      - name: Clean up
        run: |
          echo "Cleaning up..."
          rm -rf site
          echo "Cleanup complete."
      - name: Notify completion
        run: |
          echo "Deployment completed successfully!"
          echo "You can view the documentation at: https://<your-username>.github.io/<your-repo-name>/"
