name: Render PUML and Deploy Docs

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PlantUML & Graphviz
        run: sudo apt-get install -y plantuml graphviz

      - name: Render .puml to .png
        run: |
          mkdir -p rendered
          for f in c4model/*.puml; do
            plantuml -tpng "$f" -o rendered/
          done
          cp rendered/*.png c4model/

      - name: Commit rendered images
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add c4model/*.png
          git diff --staged --quiet || git commit -m "Auto-render C4 diagrams"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: render # ✅ Wait for 'render' job to finish

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Deploy MkDocs site to GitHub Pages
        run: mkdocs gh-deploy --force
